### ISSUE TITLE
Push requires credentials

### ISSUE THREAD

**Issue by lukepighetti** [extrawurst/gitui#1318]
When I try to push from within `gitui` I get a modal for username / password. When I do `git push` on the command line, it uses already established credentials. 

My expectation was that `gitui` push would work just like `git push`

**Comment by extrawurst** [comment]
depending on what platform you are on this issue might help you: https://github.com/extrawurst/gitui/issues/800

**Comment by lukepighetti** [comment]
```
printf "protocol=https\nhost=github.com\n" | git credential fill
```

produces the result 

```
protocol=https
host=github.com
username=lukepighetti
password=<REDACTED>
```

you can then type `<REDACTED>` in to this dialog

<img width="583" alt="Screen Shot 2022-09-08 at 12 30 54 PM" src="https://user-images.githubusercontent.com/666539/189176334-10eb9d21-8fb5-4a15-bed2-01a981576199.png">

But you have to enter it every time, so I have to keep this in my clipboard to be able to use `gitui` in an efficient manner. Any suggestions?

**Comment by heiskane** [comment]
Why not just use ssh keys? They work with gitui and they are much better than keeping a plaintext password to your GitHub just sitting there.

**Comment by lukepighetti** [comment]
> Why not just

It's not possible for you to introspect all of the reasons why I might be using `https` instead of ssh keys, so let's keep it on topic. The short version is every git tool I use works with my setup except for gitui, which is why this request for support is reasonable.

**Comment by heiskane** [comment]
> 

To be clear the request is reasonable. Was genuinely curious as to why https was needed.

**Comment by nispr** [comment]
> Why not just use ssh keys?
FYI, it does not seem plug&play. I had problems with gitui even when using SSH since the very beginning. Managed to solve it with #1185.

https://github.com/extrawurst/gitui/issues/1185#issuecomment-1236225011

**Comment by lukepighetti** [comment]
anti-stale

**Comment by fbreuer** [comment]
For me, this is fixed on master as per #800.

Requires `git config --global credential.helper osxkeychain` (on mac).

**Comment by cauliyang** [comment]
@fbreuer, fix my issue as well. Thanks!

**Comment by cauliyang** [comment]
> For me, this is fixed on master as per #800.
> 
> Requires `git config --global credential.helper osxkeychain` (on mac).

@fbreuer, fix my issue as well. Thanks!

**Comment by tmke8** [comment]
> Requires `git config --global credential.helper osxkeychain` (on mac).

This also fixed it for me, but I'm a bit curious why it's necessary. When I run

```
git config --list --show-origin | grep credential.helper
```

I get

```
file:/Applications/Xcode.app/Contents/Developer/usr/share/git-core/gitconfig    credential.helper=osxkeychain
file:/Users/tmke8/.gitconfig      credential.helper=osxkeychain
```

where you can see that `credential.helper=osxkeychain` was already configured on the system level. I guess `gitui` doesn't read in the system-level config file `/Applications/Xcode.app/Contents/Developer/usr/share/git-core/gitconfig`?

**Comment by Gann4Life** [comment]
In case anyone is still having issues with this, I have solved it by installing `git-credential-manager`.
I'm on **Windows** and I'm using these tools through scoop. (`git`, `gitui`, `git-credential-manager`)
After *gcm* is installed, I ran the following commands on powershell:
```powershell
git-credential-manager configure
git-credential-manager github login
```
I don't know if this is a great solution but, at least on my side it worked just fine, the credentials prompt didn't show up anymore and I can push without issues from gitui itself.
