### ISSUE TITLE
UI bottom is unintelligible on WezTerm + Fish Shell + Catppuccin theme

### ISSUE THREAD

**Issue by gacallea** [extrawurst/gitui#2286]
**Describe the bug**

`gitui` bottom row of commands looks funny and unintelligible with WezTerm, Fish Shell, Catppuccin theme.

**To Reproduce**
1. Use WezTerm, Fish Shell, and gitUI with their own respective Catppuccin ports (Macchiato in my case but it's the same with other variants)

Relevant configs:

```toml
# wezterm.lua
[...]
config.default_prog = { "/opt/homebrew/bin/fish", "-l" }
config.color_scheme = "Catppuccin Macchiato"
[...]
```

```toml
# config.fish
fish_config theme choose "Catppuccin Macchiato"
alias gitui="gitui -t catppuccin-macchiato.ron"
```

**Expected behavior**
Clear and intelligible text

**Screenshots**

<img width="900" alt="Screenshot 2024-07-02 at 11 46 31 AM" src="https://github.com/extrawurst/gitui/assets/3269984/01034583-d1d7-4d72-8877-7747607ed73d">

**Context (please complete the following information):**
 - macOS 14.5
 - gitui nightly 2024-06-02 ()
 - rustc 1.79.0 (129f3b996 2024-06-10)

**Additional context**

- I am unsure where the problem lies
- using macOS native Terminal works fine. Even with `gitui -t catppuccin-macchiato.ron`

**Comment by gacallea** [comment]
> I got the same issue (also using Catpuccin), fixed it with these overrides to my `theme.ron`

Thanks! :)

I'm opening an issue with Catppuccin for gitui port so it can be fixed for everyone :)

**Comment by gacallea** [comment]
@Bjorn-Eric-Abr what Catppuccin variant is that for? I tried it on Macchiato but nothing changes/is fixed.

**Comment by GiggleSquid** [comment]
From a little testing it seems to be that the hex values must be capitalised. Hence why @Bjorn-Eric-Abr suggestion works?

Doesn't seem to have anything to do with the actual hex value.

**Comment by ForsakenHarmony** [comment]
It would also help to not use blue as the background for selected items, I don't think catppuccin is the only theme this is going to be problematic with

**Comment by jjellison** [comment]
This is also happening for me on zsh, however, @Bjorn-Eric-Abr 's solutino doesn't seem to fix it for me. I went through and adjusted all of the hex values to be uppercase, but random options decide to be legible? I'll also note I have my iterm set to catpuccinn frappe as well...

<img width="3600" height="1118" alt="Image" src="https://github.com/user-attachments/assets/7cfe8932-c07a-400c-9f9d-1fc0eda5e510" />

EDIT: I'm an idiot, and did not do my symbolic links correctly. @Bjorn-Eric-Abr's solution of capitalizing the Hex values works for me as well!

**Comment by ChristopheCJean** [comment]
Just for information, I have no problem on a Manjaro Linux system in the Gnome 48  environment and the original (with lowercase hex values) themes.
```bash
$ wezterm --version
wezterm 20240203-110809-5046fc22
$ gitui --version
gitui nightly 2025-02-28 (99f6967)
$ fish --version
fish, version 4.0.2
```

I also have a small function to detect the dark mode automatically:
```fish
function gitui
  set mode (gsettings get org.gnome.desktop.interface color-scheme)
  if test "$mode" = "prefer-dark"
    command gitui -t catppuccin-mocha.ron $argv
  else
    command gitui -t catppuccin-latte.ron $argv
  end
end
```
