### ISSUE TITLE
Per line staging

### ISSUE THREAD

**Issue by non-descriptive** [extrawurst/gitui#59]
Currently we can stage things only hunk by hunk or whole file at once. It would be nice to have ability to stage only current line or bunch of selected lines. 

Flow would look like something like this:
We focus on diff panel and navigate to a hunk we want to work with. 
Select lines we want to stage with arrows and some modifier key (is tui allow that kind of thing?) and press [S]tage button. If there were no selection stage current line. 

Inspired by [git-cola](https://git-cola.github.io/) behavior, but it's a gui app.

**Comment by extrawurst** [comment]
Hi @non-descriptive thanks for your interest in `gitui`! I would love to have this feature. I need to checkout options how to make this ergonomic using keyboard only. will checkout how other tools are doing this and come up with a plan!

**Comment by dufferzafar** [comment]
Lazygit does this via space. You can keep pressing space on changed lines and they'll get staged. (Same for unstage) It's pretty smooth.

**Comment by gilescope** [comment]
Hmm nice. In tig you can do '/' for break this hunk into two hunks but for some reason there are some hunks it refuses to split. Pressing space would work but being able to split a hunk at an arbitrary line would be great. Worst case you have to split twice to get at a specific line, but best case far less keystrokes (and tig compatibility).

**Comment by nbigaouette** [comment]
Using `git add -p` you can split a hunk but there is a limit to this split; this looks similar to what tig does.

I use gitup on macos (gui) and I always select exact lines with the mouse and press enter to stage. There does not seems to be a limit of split in gitup so it's probably a different mechanism behind the scene.

I would love to be able to select exact lines to stage!

**Comment by MuAlphaOmegaEpsilon** [comment]
This is one of the most important features for me regarding the use of a git client versus using git directly from the command line!

**Comment by jason0x43** [comment]
In tig you can stage an individual line from the unstaged diff by moving the cursor over it and hitting `1`. You can unstage an individual line from the staged diff in the same way.

**Comment by nyanpasu64** [comment]
Sometimes I find it useful to edit a hunk-diff in a text editor. However, most GUI Git clients don't expose that option, only `git add -p` from the command line. Additionally it's tedious to replace leading `-` or `+` with a single space.

**Comment by hasufell** [comment]
> In tig you can stage an individual line from the unstaged diff by moving the cursor over it and hitting 1. You can unstage an individual line from the staged diff in the same way.

I think `1` is a natural and easy to memorize key for this.

**Comment by teras** [comment]
I'd vote also for Space instead of "1", since "1" is already a keystroke to change "window".

**Comment by tuxlifan** [comment]
Any key to stage an individual line would be a huge improvement for me to finally be able to ditch "git gui" and stop mousing around :partying_face: 

For vim users, Shift+v would be a familiar hotkey to start selecting lines.

Thank you for gitui! :smiley:

**Comment by alex-popov-tech** [comment]
super excited for this feature, that's probably the only thing which stopps me to switch to gitui from vim-fugitive :)

**Comment by hasufell** [comment]
Here is some activity.

**Comment by ser-drephs** [comment]
It's already possible to select the lines using <kbd>Shift</kbd>+<kbd>Arrow Down/Up</kbd> on Windows. Would be nice if one could stage selected lines using <kbd>Space</kbd>.

**Comment by extrawurst** [comment]
@ser-drephs unfortunately its not trivial and did not bubble up high enough apparently for anyone who cares to go forward providing a PR :(

**Comment by extrawurst** [comment]
ok work has begun on this! this will come in shape of actually four similar features:

- [ ] discard unstaged modified lines
- [ ] stage/unstage modified lines
- [ ] discard untracked lines
- [ ] stage/unstage untracked lines

I found an inspiration that supports this and is based on libgit2: [nodegit](https://github.com/nodegit/nodegit) - it seems surprisingly complicated - this is actually the only open source example that implements those per-line operations based on libgit2 and it has a few shortcomings that I am planning to lift: no support to stage/discard lines of untracked files and no line edits across multiple hunks

anyhow, stay tuned, discarding lines is on its way:
![Screenflick Movie 104](https://user-images.githubusercontent.com/776816/110249849-90f96a80-7f78-11eb-827b-500b2c5f5ea0.gif)

**Comment by extrawurst** [comment]
ok some progress: support for staging/unstaging changes in a tracked file:

![Screenflick Movie 105](https://user-images.githubusercontent.com/776816/110398112-7a840980-8073-11eb-8c50-919114667f82.gif)

see https://github.com/extrawurst/gitui/pull/575

**Comment by non-descriptive** [comment]
It's visible on the record that you press shift to select lines, but it looks like it doesn't really displayed in the actual UI. Is it possible to change "Scroll" caption when any of modifier keys pressed? If so, it might be a good idea to land an issue that depends on the current one.

**Comment by extrawurst** [comment]
> It's visible on the record that you press shift to select lines, but it looks like it doesn't really displayed in the actual UI.

true the line selection is not yet represented in the *command bar at the bottom*

**Comment by extrawurst** [comment]
staging/unstaging in tracked files is merged. please give it a spin💪

![Screenflick Movie 108](https://user-images.githubusercontent.com/776816/110700192-f60ac580-81ef-11eb-8188-a5640a490d8f.gif)

**Comment by extrawurst** [comment]
I consider this done now, the remaining two tasks (which I consider less important) will be tackled in a followup later: https://github.com/extrawurst/gitui/issues/582

**Comment by disrupted** [comment]
@extrawurst great addition! will you publish a new release with this feature?

**Comment by extrawurst** [comment]
> @extrawurst great addition! will you publish a new release with this feature?

Yeah it’s scheduled for [0.13](https://github.com/extrawurst/gitui/milestone/8) and I am asking for more people to try it until then by building from master to make sure it’s as solid as possible

**Comment by nbigaouette** [comment]
Just tried it for say, 2 minutes, and it works well! I'll continue to use it tonight and tomorrow. I'll report if I find a problem.

Thanks a lot!!

**Comment by nbigaouette** [comment]
So I've used b5ef9b1 today. Works well! Good job :) 

The only detail I can say, and that's a nitpick, is that when I stage a line, the "line cursor" (for a lack of better term...) moves to the top of the hunk. When the hunk is large and that a couple of lines are staged, it can be annoying to move the cursor back close to the original location.

Otherwise, thank you!!

**Comment by extrawurst** [comment]
> The only detail I can say, and that's a nitpick, is that when I stage a line, the "line cursor" (for a lack of better term...) moves to the top of the hunk. 

this is a very good point: #583

**Comment by extrawurst** [comment]
@nbigaouette i just merged this into master - would love to get your feedback on this! see #583

**Comment by nbigaouette** [comment]
Excellent! Just tried it and yes, cursor stays at proper location. Good job!!

Found another bug with the line staging. If I stage all lines of a hunk line by line, I end up with a hunk that has no diff but is still present in the diff window (it should disappear, like when you stage a whole hunk).

**Comment by extrawurst** [comment]
> Excellent! Just tried it and yes, cursor stays at proper location. Good job!!
> 
> Found another bug with the line staging. If I stage all lines of a hunk line by line, I end up with a hunk that has no diff but is still present in the diff window (it should disappear, like when you stage a whole hunk).

Well that’s probably only a left-over whitespace change. Should be the same if u just insert a newline in some file. Such single newline changes are not well visualized yet. But that’s not a new issue

**Comment by nbigaouette** [comment]
True! Was only whitespaces.

Thanks!
